import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PropsWithChildren } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IRootLayoutProps extends PropsWithChildren { }

export default function RootLayout({ children }: IRootLayoutProps) {
  return (
    <html lang="pt-AO">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
